### ISSUE TITLE
Sort icons don't appear initially

### ISSUE THREAD

**Issue by jacobweber** [mitchellsimoens/Ext.ux.touch.grid#12]
Even if the store is sorted when you create the grid, the sort icons in the header don't appear until you click the header.

For example, add this to the store in horizontal.js:

``` javascript
    sorters: [{
        property: 'company',
        direction: 'ASC'
    }],
```

You won't see the sort icons. One way to fix this is to add:

``` javascript
    this.fireEvent('sort');
```

at the end of View.js's initialize() method, and add the method:

``` javascript
    updateStore: function(store) {
        this.callParent(arguments);
        if (this.initialized) {
            this.fireEvent('sort');
        }
    },
```

**Comment by mitchellsimoens** [comment]
I just pushed an update to the Sorter feature that should handle a store that is already sorted. Also included a new example sorted.html
