### ISSUE TITLE
Error when you use "features" config in its own class

### ISSUE THREAD

**Issue by jacobweber** [mitchellsimoens/Ext.ux.touch.grid#15]
In your mvc example, I moved the grid in Main.js into its own class, MainGrid.js:

``` javascript
Ext.define('Grid.view.MainGrid', {
    extend: 'Ext.ux.touch.grid.View',
    xtype : 'mainGrid',

    config: {
        tabBarPosition: 'bottom',
        title   : 'Grid',
        columns : [
            {
                header    : 'Text',
                dataIndex : 'text',
                width     : '90%'
            },
            {
                header    : 'Amount',
                dataIndex : 'amount',
                width     : '10%'
            }
        ]
    }
});
```

and used it in Main.js like this:

``` javascript
            {
                xtype   : 'mainGrid',
                store   : 'Grid'
            }
```

This works. But then I tried adding a sorting feature to MainGrid.js:

``` javascript
        features: [
            {
                ftype    : 'Ext.ux.touch.grid.feature.Sorter',
                launchFn : 'initialize'
            }
        ],
```

This gives me an error in Feature.js line 38:

TypeError: 'undefined' is not a function (evaluating 'me._features.add(feature)')

It seems to be using _features, which is also used by the Sencha config system when you use "features" as a config name.

**Comment by mitchellsimoens** [comment]
Just pushed an update to fix this. Also added to the MVC example to have the grid it's own class.

https://github.com/mitchellsimoens/Ext.ux.touch.grid/commit/2611735f942e216d7cd611b9168ceeafd3b3946a

**Comment by jacobweber** [comment]
I think you forgot one, in line 49 of Feature.js: features = me._features;

**Comment by mitchellsimoens** [comment]
True enough. Fixed!
