### ISSUE TITLE
Active edit field not being saved when calling sync on store

### ISSUE THREAD

**Issue by frankkessler** [mitchellsimoens/Ext.ux.touch.grid#17]
I looked through the code and saw that each field is only saved back to the record on the itemtap event.  Without getting crazy I threw together this hack to save the active editor field before I call sync on the store. 

Mitchell, If there is a better way in the framework to do this or if you have a design in mind for some changes, let me know and I'll code it.

``` javascript
     var index, rowEl, rec;
     current_view.fireEvent('itemtap',  current_view,  index,  rowEl,  rec,  {
           getTarget: function(name){
                 return false;
           }
      });
```

**Comment by mitchellsimoens** [comment]
How else are you wanting the value of the field to be saved to the record? On itemtap it ends the edit and saves the value to the record at that time but you have to end editing to save the value to the record.

I think I can make it more robust for blur and action events on the field to end edit.

**Comment by frankkessler** [comment]
I was almost thinking of adding a sync type wrapper function that would take the active edit field and apply the value to the record, then perform the sync on the grid store.

Another option is just creating the pre-sync function that can be run before trying to sync the store.  It would just save the current record.

If you like one of these options, let me know and I'll create a pull request.

**Comment by mitchellsimoens** [comment]
I just made the blur event on the field end the edit (new method stripped out). Also added some events. If you want you can create a pull request and we can work from there.
