### ISSUE TITLE
Multiple grid instances: sort headers broken (part 2)

### ISSUE THREAD

**Issue by jacobweber** [mitchellsimoens/Ext.ux.touch.grid#18]
In your MVC example (in Safari 5.1.7 for Mac), if I click the sort headers on one grid, then switch to the other one, clicking its sort headers sorts the first grid instead.

**Comment by mitchellsimoens** [comment]
Are you all updated? Using Safari 5.1.7 with the latest code each grid is independent of one and another.

**Comment by jacobweber** [comment]
Yep, just did the following:
- Downloaded https://github.com/mitchellsimoens/Ext.ux.touch.grid/zipball/master
- Opened mvc/index.html in Safari 5.1.7.
- Clicked the "Grid" tab.
- Clicked the "Text" columnn header. The sort arrow appeared.
- Clicked the "Grid 2" tab.
- Clicked the "Amount" columnn header. The sort arrow did not appear.
- Clicked the "Grid" tab again. The sort arrow now appeared on the "Amount" column.

**Comment by mitchellsimoens** [comment]
Oh I see, the arrow is wrong but the actual sorting is correct. Will look into it now.

**Comment by mitchellsimoens** [comment]
Just did another commit that should solve this. What was happening was the array and objects for the columns were shared instances. Little cloning and it should work as expected now. Let me know if this update still does not work for you.

**Comment by jacobweber** [comment]
Looks good...thanks!
