### ISSUE TITLE
Features are initialized twice

### ISSUE THREAD

**Issue by rolandschuetz** [mitchellsimoens/Ext.ux.touch.grid#23]
When I define features directly on the instance config they are initialized twice:

I believe we could just delete this one initFeatures call:
https://github.com/mitchellsimoens/Ext.ux.touch.grid/blob/master/Ext.ux.touch.grid/View.js#L36

Cheers
Roland

**Comment by mitchellsimoens** [comment]
The feature has a launchFn config that you can say you want the feature initialized in the constructor or initialize. There are two but only one will initialize the feature.

This one is initialized in the constructor:
https://github.com/mitchellsimoens/Ext.ux.touch.grid/blob/master/checkbox.js#L72

Where as this one is in initialize:
https://github.com/mitchellsimoens/Ext.ux.touch.grid/blob/master/editable.js#L74
