### ISSUE TITLE
Can't create multiple instances using xtype, when using features

### ISSUE THREAD

**Issue by jacobweber** [mitchellsimoens/Ext.ux.touch.grid#3]
I'm defining a grid with the "touchgridpanel" xtype, using the Sorter feature. For example:

``` javascript
Ext.define('MyGrid', {
    extend: 'Ext.Container',
    config: {
        items: {
            xtype: 'touchgridpanel',
            features : [{
                ftype    : 'Ext.ux.touch.grid.feature.Sorter',
                launchFn : 'initialize'
            }],
...
```

Then I try to create two instances of it:

``` javascript
Ext.create('MyGrid', {});
Ext.create('MyGrid', {});
```

But I get an error when creating the second one: "[Ext.create] Invalid class name or alias 'undefined' specified, must be a non-empty string".

This seems to be because of Ext.ux.touch.grid.feature.Feature line 29: "delete cfg.ftype". I'm not sure you should be deleting config values like this, since they seem to be reused across multiple instances.

If I delete that line, it works.

**Comment by jacobweber** [comment]
Actually, it modifies the original config in several places (for example, adding an "element" property to the column objects, which gets reused across multiple grids). So it seems like the easiest solution is to add "config = Ext.clone(config);" before the first line of the Ext.ux.touch.grid.View constructor. That way it will operate on a copy of the config.

**Comment by mitchellsimoens** [comment]
I pushed an update the other day that should fix this.
