### ISSUE TITLE
Changing things before _buildTpl

### ISSUE THREAD

**Issue by rolandschuetz** [mitchellsimoens/Ext.ux.touch.grid#30]
Hello Mitchell,

I would like to augment the columns config in one of my features before the tpl is build (Ext.ux.touch.grid.List::_buildTpl).

Currently the features are initialized afterwards, any tip what I should do here, or how to extend?

Thanks,
Roland

**Comment by mitchellsimoens** [comment]
You would need to override the constructor, the features are init'd after the callParent in both the constructor and initialize
