### ISSUE TITLE
Builded apk problem

### ISSUE THREAD

**Issue by alin0509** [mitchellsimoens/Ext.ux.touch.grid#34]
Hi, 
I'm trying to use your grid into my application. Everyting works fine when i run my application in my browser, but when i build it an copy the resulted apk file on my tablet it dosn't work. 
The only thing that i see is loading screen...

Can u help me.
i olso use Android Virtual Devices simulator and i have the same problem...

The tablet that i use is an evolio 10'' with 2.2.2 android version. and i use ST 2.1.1 sdk

When i  run "sencha app build native"  it create my .apk file but it remains stuck on: "Packaging your application as a native app...". Is this why it doesn't work on my tablet?

**Comment by mitchellsimoens** [comment]
This has nothing to do with Ext.ux.touch.grid
