### ISSUE TITLE
paging not working properly

### ISSUE THREAD

**Issue by dnamna** [mitchellsimoens/Ext.ux.touch.grid#4]
Do i need to add the pagesize proprety for the store?
In the example paging.js the property page.size is not added.
I alos added the pagesize property but still the same issue,the grid is not loading correctly,it keeps loading all the data.
Paging toolbar is added but the buttons next previous are not functionning.

**Comment by mitchellsimoens** [comment]
The example is working perfectly, just tried with 2.0.1 RC. Looking at the requests they have the correct paging parameters when you press next, previous and use the Go To page button.
