### ISSUE TITLE
Paging feature is buggy when using Websql / SQLite proxy

### ISSUE THREAD

**Issue by nadl84** [mitchellsimoens/Ext.ux.touch.grid#55]
Hi,

I'm using a grid whose store is based on a SQL proxy. When adding the paging feature, it looks like the store is not getting correct infos from the proxy, in particular getTotalCount which returns the number of records corresponding to pageSize and not the number of records in database.

Any ideas about this issue ?

Thanks in advance,

**Comment by mitchellsimoens** [comment]
It looks like a framework issue. Try to reproduce outside the grid and if issue exists then file a bug with the framework.
